melon_data = {
    'Honeydew': {
        'Name': 'HONEYDEW',
        'Price': 0.99,
        'Seedless': True,
        'Flesh color': None,
        'Rind color': None,
        'Weight': None,
        'Origin': None,
    },
    'Crenshaw': {
        'Name': 'CRENSHAW',
        'Price': 2.00,
        'Seedless': False,
        'Flesh color': None,
        'Rind color': None, 
        'Weight': None,
        'Origin': None,
    },
    'Crane': {
        'Name': 'CRANE',
        'Price': 2.50,
        'Seedless': False,
        'Flesh color': None,
        'Rind color': None,
        'Weight': None,
        'Origin': None,
    },
    'Casaba': {
        'Name': 'CASABA',
        'Price': 2.50,
        'Seedless': False,
        'Flesh color': None,
        'Rind color': None,
        'Weight': None,
        'Origin': None,
    },
    'Cantaloupe': {
        'Name': 'CANTALOUPE',
        'Price': 0.99,
        'Seedless': False,
        'Flesh color': None,
        'Rind color': None,
        'Weight': None,
        'Origin': None,
    }
}